### ISSUE TITLE
fairly toolset

### ISSUE THREAD

**Issue by girgink** [J535D165/datahugger#28]
Hi @J535D165, @c-martinez informed us about your software. We are also working on providing efficient access methods to research data sets for a while now, and developed https://github.com/ITC-CRIB/fairly toolset, including a Python library, command line interface, and JupyterLab extension. The toolset allows local dataset creation, metadata management, smart upload/download with smart differential push and pull mechanisms. I see that you focus on downloading files only, but support more platforms. Would you be interested to collaborate? Please have a look at our repository and let us know if you will be interested.

**Comment by J535D165** [comment]
Hi @girgink, looking forward to your response!

**Comment by J535D165** [comment]
Feel free to reopen or reach out by mail.

**Comment by girgink** [comment]
Hi @J535D165, sorry for the delayed response. Standardization of metadata is difficult. Actually standards exists; the main difficulty is that the existing research data repositories do not follow the standards. I think it is better to recognize that different repositories will have different metadata (like they have different APIs) and develop the tools accordingly. In time, we can expect to reach a better situation.

Regarding collaboration, one option might be to join forces to develop clients for different repository platform. Your software deals only with data, we go beyond that. Would you be interested to help us for the data access, so that we can focus on metadata and other aspects? We have a object-oriented, modular architecture, which is easy to extend by implementing a few abstract methods. Your experience with data access for different platforms can be very valuable in this respect.

**Comment by girgink** [comment]
PS. I cannot re-open because you closed it.
