### ISSUE TITLE
Implement pagination for max results per page

### ISSUE THREAD

**Issue by kingjr** [J535D165/datahugger#29]
Thank you very for this *very* useful resource.

I'm encountering a weird case where the downloader misses many files on `osf.io`

```
files = datahugger.get('https://osf.io/3jhtb/', 'macgregor_2019')
```

Most of the `.wav` files in the `Stimuli` directory are neither listed nor downloaded. 

Any idea?

Thank you!

**Comment by J535D165** [comment]
Thanks for the compliment @kingjr, and sorry for the inconvenience (early adaptor struggles...;0).  I see that only ten files or folders per folder are downloaded. This is pagination and needs to be implemented, for example, by following "next": https://api.osf.io/v2/nodes/3jhtb/files/osfstorage/601473e5dd2225034e58b8b8/?format=jsonapi. 

I will work on a solution and will let you know.

**Comment by kingjr** [comment]
If it helps, there is a `osfclient`  python package: e.g.
```python
from osfclient import OSF
from tqdm import tqdm

def download_osf(study, d_dir):
    project = OSF().project(study)

    store = list(project.storages)
    assert len(store) == 1
    assert store[0].name == "osfstorage"

    pbar = tqdm()
    for source in store[0].files:
        path = source.path
        if path.startswith("/"):
            path = path[1:]

        file_ = dl_dir / path

        if file_.exists():
            continue

        pbar.set_description(file_.name)
        file_.parent.mkdir(parents=True, exist_ok=True)
        with file_.open("wb") as fb:
            source.write_to(fb)
  ```
