### ISSUE TITLE
Support for external of storage at OSF

### ISSUE THREAD

**Issue by EmiliaJarochowska** [J535D165/datahugger#69]
This is such a great package, thank you :-)
It seems that support for OSF works with OSF's native storage but not external storage mounted at OSF. 
Why is it useful to include that?
OSF suports external storage, e.g. any webDAV service (except for Yoda, which for some reason doesn't work) can be added as an Add-On to an OSF project. There are many reasons to do this, e.g one can write data from software directly to osf.io by mounting the external storage as a volume on their system. For example, I use SURF Research Drive for that. 
But downloading from osf.io using datahugger doesn't seem to include the files in external storage. When I moved them to osf.io storage, it worked.

You can see my use case here: 
https://osf.io/ews27/
https://github.com/MindTheGap-ERC/LMA_utils/blob/main/Track_U_at_bottom.ipynb

**Comment by J535D165** [comment]
Thanks @EmiliaJarochowska for the suggestion. I will look into this and see if the API allows us to retrieve this data as well. I will keep you updated.
