### ISSUE TITLE
Missing dep

### ISSUE THREAD

**Issue by cheginit** [J535D165/datahugger#75]
I installed the package using pip in a new env and ran the example given in the README.

First, I got an error that `pandas` is not installed. It seems that `pandas` is a hard dep, but it's included as an optional dep in `pyproject.toml`. Then, I installed `pandas`, ran the README example (with and without quotes) and got this error:

```console
$ datahugger 10.5061/dryad.mj8m0 data1  
Error: 'stash:file-download'

Do you think this is a data repository that needs to be supported?
Please request support in the issue tracker:

	https://github.com/J535D165/datahugger/issues/new/choose
```

**Comment by MyonicS** [comment]
did not get the pandas error, but the example in readme does not work. 

> KeyError                                  Traceback (most recent call last)
[<ipython-input-2-8aec36b3d3eb>](https://localhost:8080/#) in <cell line: 4>()
      2 
      3 # download the dataset to the folder "data"
----> 4 datahugger.get("10.5061/dryad.mj8m0", "data")
5 frames
[/usr/local/lib/python3.10/dist-packages/datahugger/services.py](https://localhost:8080/#) in _get_attr_link(self, record, base_url)
    103 
    104     def _get_attr_link(self, record, base_url):
--> 105         return base_url + record["_links"]["stash:file-download"]["href"]
    106 
    107 
KeyError: 'stash:file-download'
KeyError: 'stash:file-download'


I tried a Zenodo repository, that worked, so it seems to be an issue with that dryad.

**Comment by IgnacioHeredia** [comment]
In any case, it seems that `pandas` should be added as a hard dependency.
