### ISSUE TITLE
Support SeaNoe repository

### ISSUE THREAD

**Issue by IgnacioHeredia** [J535D165/datahugger#84]
Hi,

I would like ask for support for the [SeaNoe](https://www.seanoe.org/) repository.
DOI example: [10.17882/101042](https://doi.org/10.17882/101042)

In principle I cannot implement this, though someone on the @ai4eosc team might be able to do it (at some point). Guidance on the task is welcomed. ;)

Regarding whether this should be implemented as a separate repository to support, I have a issue similar to  https://github.com/J535D165/datahugger/issues/78. The SeaNoe repository seems to [exist in re3data](https://www.re3data.org/search?query=seanoe) (DataOne) but trying to download the above DOI directly with Datahugger does not work, even though Dataverse is in theory  [supported by Datahugger](https://j535d165.github.io/datahugger/repositories/). Any ideas @J535D165 ? How does one makes sure if a repository is indeed supported by Dataverse?

Thanks!

**Comment by micafer** [comment]
It seems that is has a REST API:
https://www.seanoe.org/html/api.htm

**Comment by IgnacioHeredia** [comment]
Yep. And we do have contact with the Seanoe repository developers in case we face problems (they belong to iMagine). 

Are you up to the task @micafer ? 😉

**Comment by micafer** [comment]
I can take a look.

**Comment by J535D165** [comment]
Part of 0.13.
