### ISSUE TITLE
Support `data.europa.eu`

### ISSUE THREAD

**Issue by IgnacioHeredia** [J535D165/datahugger#86]
**What's the name and URL of the repository?**
_Name_: European data
_URL_: https://data.europa.eu/

It would be a great addition to the catalogue, as it hosts almost **1.8 million** datasets!

**Does the repository support DOIs? If so, please provide one or more DOIs**
The repository does not support DOIs, but has unique IDs. For example one such dataset:
http://data.europa.eu/88u/dataset/65e092e4009f18f050b14216

**Are you interested in implementing support for this repository in Datahugger**
I'm not sure if one can use Datahugger with data reposiories not supporting DOIs. @micafer can you confirm? If possible, would you be willing to add support for this?

Thanks!

**Comment by IgnacioHeredia** [comment]
> Hi @IgnacioHeredia, Datahugger supports downloading data from repos wihout DOIs.
> It only requires the repo to have an API to list the files and download them.

That's great! Indeed several APIs [seem to be available](https://data.europa.eu/en/which-apis-are-available-and-where-can-i-find-information-about-them). Will you be willing to give this a try?

**Comment by J535D165** [comment]
Part of version 0.13.
